name: Dependabot auto-merge
on: pull_request

permissions: {}

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v3
        with:
          github-token: "${{secrets.GITHUB_TOKEN}}"
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash --subject "${PR_TITLE}" "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          PR_TITLE: ${{github.event.pull_request.title}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
